apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: video-frontend
spec:
  replicas: 3
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: video-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: video-frontend
    spec:
      containers:
        - name: frontend
          image: meghanamanchala/video-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: INTERNAL_API_URL
              value: "http://backend-service:8000"
            - name: NEXT_PUBLIC_API_URL
              value: "http://api.academix.local"
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: publishable-key
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: secret-key
            - name: DISABLE_AUTH
              value: "true"

          startupProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 1

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
