apiVersion: v1
kind: Secret
metadata:
  name: clerk-secrets
type: Opaque
stringData:
  publishable-key: "<set-via-github-secret-or-local-env>"
  secret-key: "<set-via-github-secret-or-local-env>"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
stringData:
  username: "<set-via-github-secret-or-local-env>"
  password: "<set-via-github-secret-or-local-env>"
