apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "video-processing-platform.fullname" . }}-backend-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-processing-platform.fullname" . }}-backend
  labels:
    app: {{ include "video-processing-platform.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "video-processing-platform.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "video-processing-platform.name" . }}-backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: password
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@{{ include "video-processing-platform.fullname" . }}-mongo-service:27017"
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.backend.featureFlags }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "video-processing-platform.fullname" . }}-backend-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-processing-platform.fullname" . }}-backend-service
spec:
  selector:
    app: {{ include "video-processing-platform.name" . }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
