backend:
  replicaCount: 1
  image:
    tag: dev
  resources:
    requests:
      cpu: 75m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  featureFlags:
    ENABLE_AI_SUMMARY: "false"
    ENABLE_LIVE_SUMMARY: "false"
  env:
    MONGO_DB_NAME: video_platform_dev
    UPLOAD_DIR: /app/uploads
    MAX_UPLOAD_BYTES: "524288000"

frontend:
  replicaCount: 1
  image:
    tag: dev
  publicApiUrl: http://api.dev.academix.local
  resources:
    requests:
      cpu: 75m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  featureFlags:
    NEXT_PUBLIC_ENABLE_ADVANCED_INSIGHTS: "false"

ingress:
  hosts:
    - host: app.dev.academix.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
    - host: api.dev.academix.local
      paths:
        - path: /
          pathType: Prefix
          service: backend
          port: 8000

mongodb:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    size: 5Gi

# Use this secret if GHCR packages are private.
# Create it with: kubectl create secret docker-registry ghcr-pull-secret ...
imagePullSecrets:
  - ghcr-pull-secret
